CREATE SCHEMA IF NOT EXISTS agent_cloud;
SET search_path TO agent_cloud;
CREATE TABLE IF NOT EXISTS schema_version (id INTEGER PRIMARY KEY CHECK(id=1), version INTEGER NOT NULL);
INSERT INTO schema_version VALUES(1,1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY, owner TEXT NOT NULL, title TEXT NOT NULL,
    status TEXT NOT NULL, created DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY, session_id TEXT NOT NULL REFERENCES sessions(id),
    turn_id TEXT UNIQUE NOT NULL, idem TEXT NOT NULL, text TEXT NOT NULL, status TEXT NOT NULL,
    created DOUBLE PRECISION NOT NULL, updated DOUBLE PRECISION NOT NULL, answer TEXT, error TEXT,
    UNIQUE(session_id,idem));
CREATE TABLE IF NOT EXISTS events(seq BIGSERIAL PRIMARY KEY, job_id TEXT NOT NULL REFERENCES jobs(id),
    status TEXT NOT NULL, at DOUBLE PRECISION NOT NULL, detail TEXT, event_key TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS progress_identity ON events(job_id,event_key) WHERE event_key IS NOT NULL;
CREATE TABLE IF NOT EXISTS evidence(id TEXT PRIMARY KEY, session_id TEXT NOT NULL REFERENCES sessions(id),
    turn_id TEXT NOT NULL, kind TEXT NOT NULL, label TEXT NOT NULL, payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS routing(job_id TEXT PRIMARY KEY REFERENCES jobs(id) ON DELETE CASCADE, payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS executions(job_id TEXT PRIMARY KEY REFERENCES jobs(id) ON DELETE CASCADE,
    token TEXT UNIQUE NOT NULL, deadline DOUBLE PRECISION NOT NULL, finished BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS budgets(id INTEGER PRIMARY KEY CHECK(id=1), payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS login_limits(key TEXT PRIMARY KEY, attempts INTEGER NOT NULL, expires DOUBLE PRECISION NOT NULL);
CREATE INDEX IF NOT EXISTS sessions_owner ON sessions(owner,created);
CREATE INDEX IF NOT EXISTS jobs_session ON jobs(session_id,created);
CREATE INDEX IF NOT EXISTS events_job ON events(job_id,seq);
