import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const root='state/scope-routing';await fs.mkdir(root,{recursive:true});
const base=process.env.WEB_TEST_URL||'http://127.0.0.1:8767';
const browser=await chromium.launch({channel:'chrome',headless:true});
const ctx=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page=await ctx.newPage();const errors=[],checks=[];
page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>assert.equal(new URL(r.url()).hostname,'127.0.0.1'));
const health=()=>ctx.request.get(base+'/api/health').then(r=>r.json());
const session=async()=>ctx.request.get(base+'/api/sessions/'+await page.evaluate(()=>localStorage.getItem('selectedSession'))).then(r=>r.json());
const send=async text=>{await page.locator('#question').fill(text);await page.getByRole('button',{name:'发送问题',exact:true}).click();};
const local=async text=>{await send(text);await page.locator('.turn').last().locator('.scope-reply').waitFor();};
const done=async()=>{await page.locator('.turn').last().locator('.status.verified').waitFor({timeout:900000});return (await session()).jobs.at(-1);};
const fresh=async()=>{await page.getByRole('button',{name:'＋ 新建对话',exact:true}).click();await page.locator('.welcome').waitFor();};
const shot=async name=>{await page.screenshot({path:root+'/'+name+'.png',fullPage:true,animations:'disabled'});console.log(name);};
try{
 await page.goto(base);await page.getByRole('button',{name:'版本对比',exact:true}).waitFor();
 const before=(await health()).budget.request_count;
 await local('你好');await local('帮我看看今天的天气');await local('我想预测玩家流失');
 assert.equal((await health()).budget.request_count,before);
 assert.equal((await session()).status,'open');assert.equal(await page.locator('.failure').count(),0);
 await shot('01-local-boundaries');checks.push('greeting/weather/unsupported metric: no model attempts, session remains open');
 await local('剧情开始情况怎么样');const sid=(await session()).id;
 await page.reload();await page.locator('.scope-reply').last().waitFor();
 await page.locator('.scope-reply').last().getByRole('button',{name:'查看后一次更新',exact:true}).click();
 assert.equal(await page.locator('#question').inputValue(),'查看后一次更新');
 assert.equal((await health()).budget.request_count,before);
 await page.getByRole('button',{name:'发送问题',exact:true}).click();let j=await done();
 assert.equal(j.status,'succeeded');assert.deepEqual(j.routing.plan.versions,['V6']);
 assert.ok(j.evidence.filter(e=>e.kind==='claims').every(e=>e.fact.scope.version_id==='V6'));
 assert.equal((await session()).id,sid);checks.push('persisted clarification choice, no auto-submit, real V6 query');
 await send('那前一次更新呢？');j=await done();assert.deepEqual(j.routing.plan.versions,['V5']);
 assert.ok(j.evidence.filter(e=>e.kind==='claims').every(e=>e.fact.scope.version_id==='V5'));
 checks.push('follow-up changes version without changing metric');
 await fresh();await send('比较前一次和后一次更新的剧情开始情况，为什么会这样？');j=await done();
 assert.equal(j.status,'partial');assert.ok(j.answer.limitations.length);assert.ok(j.evidence.some(e=>e.fact.field==='percentage_point_difference'));
 await page.locator('.partial-notice').waitFor();await shot('02-partial-analysis');
 const dl=page.waitForEvent('download');await page.getByRole('button',{name:'下载分析',exact:true}).click();
 await (await dl).saveAs(root+'/partial-export.md');assert.ok((await fs.readFile(root+'/partial-export.md','utf8')).includes('未能完成的部分'));
 checks.push('partial completion contains actual comparison evidence and exports limits');
 await fresh();await send('查看前一次更新的玩家分组');j=await done();assert.equal(j.routing.plan.snapshot,'replay_V5main');
 await send('那第二组呢？');j=await done();assert.equal(j.routing.plan.group,'G02');
 assert.ok(j.evidence.every(e=>e.fact.selection.scope.segment_id==='G02'&&e.fact.selection.scope.snapshot_id==='replay_V5main'));
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('03-group-followup-mobile');
 checks.push('real frozen snapshot and group follow-up, mobile layout');await page.setViewportSize({width:1440,height:1000});
 await fresh();await send('玩地图探索的玩家，也会玩支线体验吗？');j=await done();
 assert.ok(j.evidence.every(e=>e.fact.antecedent[0]==='地图探索'&&e.fact.consequent[0]==='支线体验'));
 await shot('04-new-rule-pair');checks.push('new gameplay pair resolves actual matching frozen rule, no substitution');
 await fresh();await send('查看前一次更新的剧情参与预测');j=await done();
 assert.ok(j.evidence.every(e=>e.fact.scope.version_id==='V5'));checks.push('real parameterized V5 prediction');
 await fresh();const count=(await health()).budget.request_count;
 await local('V6 北京地区的剧情开始比例');assert.equal((await health()).budget.request_count,count);
 assert.equal((await session()).jobs.at(-1).text,'V6 北京地区的剧情开始比例');checks.push('unknown qualifiers retained; no invented filter or silently broader query');
 assert.deepEqual(errors,[]);
 await fs.writeFile(root+'/browser-results.json',JSON.stringify({status:'PASS',browser:await browser.version(),mode:'offline rules + real DSH/MCP; not live language-model validation',checks,errors},null,2));
}catch(e){await shot('failure-debug');await fs.writeFile(root+'/browser-results.json',JSON.stringify({status:'FAIL',error:String(e),checks,errors},null,2));throw e;}
finally{await browser.close();}
